name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main
    paths:
      - "api-server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Create private key file
        run: echo "${{ secrets.PRIVATE_KEY }}" > ec2-key.pem

      - name: Set permissions for private key
        run: chmod 400 ec2-key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
            if [ ! -d "Deployify/api-server" ]; then
              git clone ${{secrets.SERVER_GITHUB_URL}}
            fi

            cd Deployify/api-server

            git pull origin main

            npm install

            cat > .env << 'EOL'
            ACCESS_KEY_ID=${{secrets.EC2_ACCESS_KEY_ID}} 
            SECRET_ACCESS_KEY=${{secrets.EC2_SECRET_ACCESS_KEY}}
            REGION=${{secrets.EC2_REGION}}
            BUCKET_NAME=${{secrets.EC2_BUCKET_NAME}}
            TASK_DEFINITION=${{secrets.EC2_TASK_DEFINITION}}
            CLUSTER_DEFINITION=${{secrets.EC2_CLUSTER_DEFINITION}}
            SUBNETS=${{secrets.EC2_SUBNETS}}
            SECURITY_GROUPS=${{secrets.EC2_SECURITY_GROUPS}}
            EOL

            pm2 restart index.js || pm2 start index.js --name "api-server"

            echo "Deployment completed successfully"
          EOF

      - name: Cleanup private key
        run: rm -f ec2-key.pem

      - name: Successful message
        run: echo "Deployment was successful"
